### ISSUE TITLE
ptp4l and gPTP relationship

### ISSUE THREAD

**Issue by elabbing** [Avnu/tsn-doc#14]
Goodmorning,
I approached TSN-AVB networks by Avnu repository.
In Avnu repository we can find `gPTP`, but in TSN-docs said using `ptp4l`.
It seems that `gPTP` implementation could be omitted, almost usefuless.
Please, could you clarifying me about this point?

Thanks a lot.
Best regards

**Comment by andrew-elder** [comment]
I know that several years ago `gPTP` was been run through the Avnu certification PTP test suite, I don't know that mainline `ptp4l` has had the same testing. Maybe someone else has more information on that subject?

**Comment by vedangpatel1** [comment]
in TSN-doc, we are focusing on the TSN features provided by the mainline projects like linux kernel and linuxptp. These components are easily accessible to users on most distributions. ptp4l is part of linuxptp which is why we are focusing on it.

Also, the way gPTP and ptp4l  supply timestamps to the application is different. Which makes them incompatible with each other and the applications using them. So, we cannot suggest it as an alternative way to synchronize time.

Let me know if you have more questions about this.

**Comment by aguedes** [comment]
It seems the issue has been clarified so I'm closing it.
